import { LibraryItem } from './data';

export const PAPERS2_DATA: LibraryItem[] = [
  // SECTION 8: Robotics & Embodied AI Papers
  { id: 'p8-1', title: 'End-to-End Learning for Self-Driving Cars', author: 'Bojarski et al. (NVIDIA)', year: '2016', significance: 'CNN end-to-end driving; embodied AI milestone', type: 'paper', section: 'Robotics & Embodied AI Papers', venue: 'arXiv' },
  { id: 'p8-2', title: 'Learning Dexterous In-Hand Manipulation (Dactyl)', author: 'Andrychowicz et al. (OpenAI)', year: '2018', significance: 'Rubik\'s cube robot hand; sim-to-real transfer', type: 'paper', section: 'Robotics & Embodied AI Papers', venue: 'arXiv' },
  { id: 'p8-3', title: 'Solving Rubik\'s Cube with a Robot Hand', author: 'OpenAI', year: '2019', significance: 'Physical dexterity via RL; domain randomization', type: 'paper', section: 'Robotics & Embodied AI Papers', venue: 'arXiv' },
  { id: 'p8-4', title: 'Decision Transformer: RL via Sequence Modeling', author: 'Chen et al.', year: '2021', significance: 'RL reframed as sequence prediction; offline RL', type: 'paper', section: 'Robotics & Embodied AI Papers', venue: 'NeurIPS' },
  { id: 'p8-5', title: 'Do As I Can, Not As I Say: Grounding Language in Robotic Affordances (SayCan)', author: 'Ahn et al. (Google)', year: '2022', significance: 'LLM + robot grounding; embodied AI', type: 'paper', section: 'Robotics & Embodied AI Papers', venue: 'arXiv' },
  { id: 'p8-6', title: 'PaLM-E: An Embodied Multimodal Language Model', author: 'Driess et al. (Google)', year: '2022', significance: 'Largest embodied model; vision + language + action', type: 'paper', section: 'Robotics & Embodied AI Papers', venue: 'arXiv' },
  { id: 'p8-7', title: 'RT-2: Vision-Language-Action Models Transfer Web Knowledge to Robotic Control', author: 'Brohan et al. (Google DeepMind)', year: '2023', significance: 'Web-trained VLA model for robotic control', type: 'paper', section: 'Robotics & Embodied AI Papers', venue: 'arXiv' },
  { id: 'p8-8', title: 'ELLMER Framework: Robotic Arm with Language Instructions in Dynamic Environments', author: 'University of Edinburgh', year: '2025', significance: 'Robotic arm making coffee autonomously; real-time adaptation', type: 'paper', section: 'Robotics & Embodied AI Papers', venue: 'Nature Machine Intelligence' },

  // SECTION 9: AI Alignment & Safety Research Papers
  { id: 'p9-1', title: 'Concrete Problems in AI Safety', author: 'Amodei, Olah et al. (OpenAI/Google)', year: '2016', significance: 'Reward hacking; safe exploration; distributional shift; side effects', type: 'paper', section: 'AI Alignment & Safety Papers', venue: 'arXiv' },
  { id: 'p9-2', title: 'Safely Interruptible Agents', author: 'Orseau & Armstrong (DeepMind)', year: '2016', significance: 'Big Red Button problem; corrigible AI', type: 'paper', section: 'AI Alignment & Safety Papers', venue: 'UAI 2016' },
  { id: 'p9-3', title: 'AI Safety via Debate', author: 'Irving et al. (OpenAI)', year: '2017', significance: 'Two AIs debate for oversight; scalable alignment', type: 'paper', section: 'AI Alignment & Safety Papers', venue: 'arXiv' },
  { id: 'p9-4', title: 'Supervising Strong Learners by Amplifying Weak Experts', author: 'Christiano et al.', year: '2018', significance: 'Iterated amplification; scalable oversight', type: 'paper', section: 'AI Alignment & Safety Papers', venue: 'arXiv' },
  { id: 'p9-5', title: 'Aligning AI With Shared Human Values', author: 'Hendrycks et al.', year: '2020', significance: 'ETHICS benchmark; moral reasoning in LLMs', type: 'paper', section: 'AI Alignment & Safety Papers', venue: 'arXiv' },
  { id: 'p9-6', title: 'TruthfulQA: Measuring How Models Mimic Human Falsehoods', author: 'Lin et al.', year: '2021', significance: 'AI truthfulness; hallucination measurement', type: 'paper', section: 'AI Alignment & Safety Papers', venue: 'ACL 2022' },
  { id: 'p9-7', title: 'Risks from Learned Optimization in Advanced Machine Learning Systems (Mesa-Optimization)', author: 'Hubinger et al.', year: '2021', significance: 'Inner alignment; deceptive mesa-optimizers', type: 'paper', section: 'AI Alignment & Safety Papers', venue: 'arXiv' },
  { id: 'p9-8', title: 'Training Language Models to Follow Instructions with Human Feedback', author: 'Ouyang et al. (OpenAI)', year: '2022', significance: 'InstructGPT; RLHF alignment method', type: 'paper', section: 'AI Alignment & Safety Papers', venue: 'NeurIPS' },
  { id: 'p9-9', title: 'Constitutional AI: Harmlessness from AI Feedback', author: 'Bai et al. (Anthropic)', year: '2022', significance: 'RLAIF; principle-based training; AI feedback loop', type: 'paper', section: 'AI Alignment & Safety Papers', venue: 'arXiv' },
  { id: 'p9-10', title: 'Red Teaming Language Models to Reduce Harms', author: 'Ganguli et al. (Anthropic)', year: '2022', significance: 'Systematic adversarial testing for LLM safety', type: 'paper', section: 'AI Alignment & Safety Papers', venue: 'arXiv' },
  { id: 'p9-11', title: 'Discovering Language Model Behaviors with Model-Written Evaluations', author: 'Perez et al. (Anthropic)', year: '2022', significance: 'Model-generated evals; sycophancy and power-seeking', type: 'paper', section: 'AI Alignment & Safety Papers', venue: 'ACL 2023' },
  { id: 'p9-12', title: 'Scalable Oversight of AI Systems via Debate', author: 'Bowman et al.', year: '2023', significance: 'Human-AI debate for scalable oversight', type: 'paper', section: 'AI Alignment & Safety Papers', venue: 'arXiv' },
  { id: 'p9-13', title: 'Sleeper Agents: Training Deceptive LLMs that Persist Through Safety Training', author: 'Hubinger et al. (Anthropic)', year: '2023', significance: 'Deceptive alignment; RLHF cannot remove all unsafe behavior', type: 'paper', section: 'AI Alignment & Safety Papers', venue: 'arXiv' },
  { id: 'p9-14', title: 'Model Evaluation for Extreme Risks', author: 'Anthropic', year: '2023', significance: 'Dangerous capability evaluation framework', type: 'paper', section: 'AI Alignment & Safety Papers', venue: 'arXiv' },
  { id: 'p9-15', title: 'The Claude Model Spec (Model Card & Character)', author: 'Anthropic', year: '2024', significance: 'Constitutional values, character, safety hierarchy for Claude', type: 'paper', section: 'AI Alignment & Safety Papers', venue: 'Anthropic' },
  { id: 'p9-16', title: 'Representation Engineering: A Top-Down Approach to AI Transparency', author: 'Zou et al.', year: '2024', significance: 'Interpretability via representation vectors', type: 'paper', section: 'AI Alignment & Safety Papers', venue: 'arXiv' },
  { id: 'p9-17', title: 'Scaling Monosemanticity: Extracting Interpretable Features from Claude Sonnet', author: 'Templeton et al. (Anthropic)', year: '2024', significance: 'Sparse autoencoders for feature extraction; interpretability', type: 'paper', section: 'AI Alignment & Safety Papers', venue: 'Anthropic Research' },

  // SECTION 10: Mechanistic Interpretability Papers
  { id: 'p10-1', title: 'Attention Is Not Explanation', author: 'Jain & Wallace', year: '2017', significance: 'Attention weights do not explain model predictions', type: 'paper', section: 'Mechanistic Interpretability Papers', venue: 'NAACL 2019' },
  { id: 'p10-2', title: 'Zoom In: An Introduction to Circuits', author: 'Olah et al. (OpenAI)', year: '2020', significance: 'Mechanistic interpretability; circuits in neural networks', type: 'paper', section: 'Mechanistic Interpretability Papers', venue: 'Distill' },
  { id: 'p10-3', title: 'A Mathematical Framework for Transformer Circuits', author: 'Elhage et al. (Anthropic)', year: '2021', significance: 'Formal mechanistic interpretability of transformers', type: 'paper', section: 'Mechanistic Interpretability Papers', venue: 'Transformer Circuits Thread' },
  { id: 'p10-4', title: 'In-Context Learning and Induction Heads', author: 'Olsson et al. (Anthropic)', year: '2022', significance: 'Mechanistic basis for few-shot learning', type: 'paper', section: 'Mechanistic Interpretability Papers', venue: 'Transformer Circuits Thread' },
  { id: 'p10-5', title: 'Toy Models of Superposition', author: 'Elhage et al. (Anthropic)', year: '2022', significance: 'Superposition; features compete for neurons', type: 'paper', section: 'Mechanistic Interpretability Papers', venue: 'Transformer Circuits Thread' },
  { id: 'p10-6', title: 'Towards Monosemanticity: Decomposing Language Models with Dictionary Learning', author: 'Bricken et al. (Anthropic)', year: '2023', significance: 'Sparse autoencoders; monosemantic features', type: 'paper', section: 'Mechanistic Interpretability Papers', venue: 'Transformer Circuits Thread' },
  { id: 'p10-7', title: 'Scaling and Evaluating Sparse Autoencoders', author: 'Gao et al. (OpenAI)', year: '2024', significance: 'Scaling interpretability with sparse autoencoders', type: 'paper', section: 'Mechanistic Interpretability Papers', venue: 'arXiv' },

  // SECTION 11: Multimodal AI Papers
  { id: 'p11-1', title: 'Learning Transferable Visual Models From Natural Language Supervision (CLIP)', author: 'Radford et al. (OpenAI)', year: '2021', significance: 'Vision-language alignment; zero-shot image classification', type: 'paper', section: 'Multimodal AI Papers', venue: 'ICML' },
  { id: 'p11-2', title: 'Flamingo: A Visual Language Model for Few-Shot Learning', author: 'Alayrac et al. (DeepMind)', year: '2022', significance: 'Visual question answering; few-shot multimodal', type: 'paper', section: 'Multimodal AI Papers', venue: 'NeurIPS' },
  { id: 'p11-3', title: 'GPT-4V(ision) System Card', author: 'OpenAI', year: '2023', significance: 'Vision-capable GPT-4; multimodal understanding', type: 'paper', section: 'Multimodal AI Papers', venue: 'OpenAI Technical Report' },
  { id: 'p11-4', title: 'LLaVA: Large Language and Vision Assistant', author: 'Liu et al.', year: '2023', significance: 'Open-source multimodal instruction tuning', type: 'paper', section: 'Multimodal AI Papers', venue: 'NeurIPS' },
  { id: 'p11-5', title: 'Gemini: A Family of Highly Capable Multimodal Models', author: 'Google DeepMind', year: '2024', significance: 'Natively multimodal; text, image, audio, video, code', type: 'paper', section: 'Multimodal AI Papers', venue: 'arXiv' },
  { id: 'p11-6', title: 'GPT-4o Technical Report', author: 'OpenAI', year: '2024', significance: 'Omni model; real-time multimodal conversation', type: 'paper', section: 'Multimodal AI Papers', venue: 'OpenAI Technical Report' },
  { id: 'p11-7', title: 'Claude 3.5 Sonnet Model Card', author: 'Anthropic', year: '2024', significance: 'Vision, reasoning, coding at frontier level', type: 'paper', section: 'Multimodal AI Papers', venue: 'Anthropic' },
];
